# Generated by Django 2.1.2 on 2018-12-13 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('couriertrack', '0002_parceldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel', to='couriertrack.ParcelData')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='couriertrack.StatusData')),
            ],
        ),
    ]
